version: 0.1
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm i -g serverless
      - npm i
      - chmod +x deploy.sh
  build:
    commands:
      - ./deploy.sh
  post_build:
    commands:
      - echo Build completed on `date`

cache:
  paths:
    - node_modules/**/*
