AWSTemplateFormatVersion: "2010-09-09"
Description: The AWS CloudFormation template to create user credentials secret manager.

Resources:
  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'SecretsManager to Store database Credentials'
      Name: '/${self:provider.stage}/${self:service}/database/credentials'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "","password": "","host": "","database": "", "port": ""}'
        GenerateStringKey: "password"
        PasswordLength: 30
        RequireEachIncludedType: true
        ExcludePunctuation: false
        ExcludeCharacters: '"@/\'
